COU200.PGM: COU200.RPG COUNTRY.FILE COU200D.FILE
CSTNAME.PGM: CSTNAME.SQLRPG QPROTOSRC/VAR1.RPG
CUSTINFO.PGM: CUSTINFO.RPG QPROTOSRC/CPYBK1.RPG QPROTOSRC/CPYBK2.RPG
ADDN.PGM: ADDN.RPG QPROTOSRC/CPY01.RPGINC